// Alphabetically ordered
const Tasks = {
	BUILD: 'BUILD',
	DEPOSIT_ENERGY: 'DEPOSIT_ENERGY',
	HARVEST: 'HARVEST',
	REPAIR: 'REPAIR',
	SUPPLY_SPAWN: 'SUPPLY_SPAWN',
	SUPPLY_SPAWN_EXTENSIONS: 'SUPPLY_SPAWN_EXTENSIONS',
	UPGRADE_ROOM: 'UPGRADE_ROOM',
}

export default Tasks;
